#!/bin/bash

# Stop process if some command fails.
set -e

# Extracting parameters.
VERSION_TYPE=${1}

# Version increase type validation.
if [[ "$VERSION_TYPE" != "patch" && "$VERSION_TYPE" != "minor" && "$VERSION_TYPE" != "major" ]]; then
  echo "Error: Invalid version increase type, expected values: [patch, minor, major]"
  exit 1
fi

# Branch to manage.
BRANCH_DEST="main"
BRANCH_SOURCE="$(git rev-parse --abbrev-ref HEAD)"

# 1. Increase Project version
echo "Increasing project version ..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/../config/config.js"
CURRENT_VERSION=$(sed -n "s/.*version: *['\"]\([^'\"]*\)['\"].*/\1/p" "$CONFIG_FILE")
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
echo "Current version: $CURRENT_VERSION"

if [[ "$VERSION_TYPE" == "patch" ]]; then
    PATCH=$((PATCH + 1))
elif [[ "$VERSION_TYPE" == "minor" ]]; then
    MINOR=$((MINOR + 1))
    PATCH=0
elif [[ "$VERSION_TYPE" == "major" ]]; then
    MAJOR=$((MAJOR + 1))
    MINOR=0
    PATCH=0
fi

NEW_VERSION="$MAJOR.$MINOR.$PATCH"
echo "New version: $NEW_VERSION"
echo "window.APP_VERSION = { version: '$NEW_VERSION' };" > $CONFIG_FILE

# Commit and PR information.
COMMIT_MSG="Deploying project version $NEW_VERSION via Shell"
PR_TITLE="PR for version $NEW_VERSION from $BRANCH_SOURCE to $BRANCH_DEST"
PR_BODY="Pull request for version $NEW_VERSION automatically generated by sh script"

# 3. Git Commit and Push
echo "Committing e pushing ..."
git add .
git commit -m "$COMMIT_MSG" || echo "No change to commit"
git push origin "$BRANCH_SOURCE"

# 4. Pull Request (via GitHub CLI)
echo "Creating pull request to $BRANCH_DEST ..."
gh pr create --base "$BRANCH_DEST" --head "$BRANCH_SOURCE" --title "$PR_TITLE" --body "$PR_BODY"

# 5. End Script
echo "Deploy completed successfully"